### ISSUE TITLE
Code blocks are rendered incorrectly if they come after text without a new line

### ISSUE THREAD

**Issue by MrEbbinghaus** [askonomm/clarktown#14]
```markdown
    Example:
    ```clojure 
    (def spouse 
      {:name "Alice"
       :profile-pic-href "alice.png"})
    ```
```

gets rendered like:

![image](https://user-images.githubusercontent.com/2965273/163156178-459eb856-5e60-4289-a42f-ba5601ed4230.png)

HTML:
```html
<p>Example:
<code></code>`clojure 
(def spouse 
  {:name "Alice"
   :profile-pic-href "alice.png"})</p>
```

**Comment by MrEbbinghaus** [comment]
Same when there is no empty line after the code block:

```markdown
    ```clojure
    :foo
    ```
    Now the ugly update function from above becomes as simple as:
    
    ```clojure
    :bar
    ```
```

renders like:
![image](https://user-images.githubusercontent.com/2965273/163157351-93b3608f-1065-4d32-aa90-6c8742c362fe.png)

**Comment by askonomm** [comment]
This is by design. Clarktown parses blocks, and blocks are created by having two line breaks in-between. Thus, your example is just one block of text as far as Clarktown is concerned and not two different ones. And since the block starts with regular text, it determines it's just a paragraph and not a code block, which starts with with the uptick characters. You really want to have two line breaks between blocks.

To make this work would require some significant rewrite of the underlying architecture as the whole premise is built under the idea that blocks are separated by two newlines.
